// =================================================================
// Generated by C64U Python-to-6502 Transpiler
// Target Assembler: KickAssembler
// Start Address:    $0801
// =================================================================

BasicUpstart2(start)

* = $0810 "Main Program"

// Constant Definitions
.const CHROUT = $FFD2
.const CIA1_PRA = $DC00
.const CIA1_PRB = $DC01
.const COLOR_BLACK = $00
.const COLOR_BLUE = $06
.const COLOR_BROWN = $09
.const COLOR_CYAN = $03
.const COLOR_DARK_GREY = $0B
.const COLOR_GREEN = $05
.const COLOR_GREY = $0C
.const COLOR_LIGHT_BLUE = $0E
.const COLOR_LIGHT_GREEN = $0D
.const COLOR_LIGHT_GREY = $0F
.const COLOR_LIGHT_RED = $0A
.const COLOR_ORANGE = $08
.const COLOR_PURPLE = $04
.const COLOR_RAM = $D800
.const COLOR_RED = $02
.const COLOR_WHITE = $01
.const COLOR_YELLOW = $07
.const GETIN = $FFE4
.const PLOT = $FFF0
.const RASTER = $D012
.const SCNKEY = $FF9F
.const SCREEN_RAM = $0400
.const SID_BASE = $D400
.const SID_V1_AD = $D405
.const SID_V1_CTRL = $D404
.const SID_V1_FREQ_HI = $D401
.const SID_V1_FREQ_LO = $D400
.const SID_V1_PW_HI = $D403
.const SID_V1_PW_LO = $D402
.const SID_V1_SR = $D406
.const SID_VOLUME = $D418
.const VIC_BG = $D021
.const VIC_BG0 = $D021
.const VIC_BG1 = $D022
.const VIC_BG2 = $D023
.const VIC_BG3 = $D024
.const VIC_BORDER = $D020
.const VIC_CTRL1 = $D011
.const VIC_CTRL2 = $D016
.const VIC_SPRITE_ENABLE = $D015
.const VIC_SPRITE_X0 = $D000
.const VIC_SPRITE_Y0 = $D001

start:
    lda #$00
    sta $D020
    lda #$00
    sta $D021
    ldx #$00
clr_loop_1:
    lda #$20
    sta $0400,x
    sta $0500,x
    sta $0600,x
    sta $06e8,x
    lda #$07
    sta $D800,x
    sta $D900,x
    sta $DA00,x
    sta $DAe8,x
    inx
    bne clr_loop_1
    ldx #$00
prt_loop_3:
    lda str_2,x
    beq prt_end_4
    jsr $FFD2               // KERNAL CHROUT
    inx
    jmp prt_loop_3
prt_end_4:
    lda #$0F
    sta $D418           // SID Volume MAX
    lda #$58
    sta $D400           // V1 Freq Lo
    lda #$22
    sta $D401           // V1 Freq Hi
    lda #$09
    sta $D405           // V1 Attack/Decay
    lda #$A0
    sta $D406           // V1 Sustain/Release
    lda #$21
    sta $D404           // V1 Control (Gate On)
    ldy #$13
dly1_5:
    ldx #$88
dly2_6:
    dex
    bne dly2_6
    dey
    bne dly1_5
    lda #$20
    sta $D404
    ldx #$00
prt_loop_8:
    lda str_7,x
    beq prt_end_9
    jsr $FFD2               // KERNAL CHROUT
    inx
    jmp prt_loop_8
prt_end_9:
    rts                     // Return to BASIC / KERNAL

// -----------------------------------------------------------------
// String Literals
// -----------------------------------------------------------------
str_2: .text "PLAYING SID SOUND CHIME..."
        .byte 0
str_7: .text "SOUND FINISHED!"
        .byte 0
