// =================================================================
// Generated by C64U Python-to-6502 Transpiler
// Target Assembler: KickAssembler
// Start Address:    $0801
// =================================================================

BasicUpstart2(start)

* = $0810 "Main Program"

// Constant Definitions
.const CHROUT = $FFD2
.const CIA1_PRA = $DC00
.const CIA1_PRB = $DC01
.const COLOR_BLACK = $00
.const COLOR_BLUE = $06
.const COLOR_BROWN = $09
.const COLOR_CYAN = $03
.const COLOR_DARK_GREY = $0B
.const COLOR_GREEN = $05
.const COLOR_GREY = $0C
.const COLOR_LIGHT_BLUE = $0E
.const COLOR_LIGHT_GREEN = $0D
.const COLOR_LIGHT_GREY = $0F
.const COLOR_LIGHT_RED = $0A
.const COLOR_ORANGE = $08
.const COLOR_PURPLE = $04
.const COLOR_RAM = $D800
.const COLOR_RED = $02
.const COLOR_WHITE = $01
.const COLOR_YELLOW = $07
.const GETIN = $FFE4
.const PLOT = $FFF0
.const RASTER = $D012
.const SCNKEY = $FF9F
.const SCREEN_RAM = $0400
.const SID_BASE = $D400
.const SID_V1_AD = $D405
.const SID_V1_CTRL = $D404
.const SID_V1_FREQ_HI = $D401
.const SID_V1_FREQ_LO = $D400
.const SID_V1_PW_HI = $D403
.const SID_V1_PW_LO = $D402
.const SID_V1_SR = $D406
.const SID_VOLUME = $D418
.const VIC_BG = $D021
.const VIC_BG0 = $D021
.const VIC_BG1 = $D022
.const VIC_BG2 = $D023
.const VIC_BG3 = $D024
.const VIC_BORDER = $D020
.const VIC_CTRL1 = $D011
.const VIC_CTRL2 = $D016
.const VIC_SPRITE_ENABLE = $D015
.const VIC_SPRITE_X0 = $D000
.const VIC_SPRITE_Y0 = $D001

start:
while_start_1:
    // Python: while True
raster_wait_3:
    lda $D012
    cmp #$32
    bne raster_wait_3
    lda #$02
    sta $D020
raster_wait_4:
    lda $D012
    cmp #$46
    bne raster_wait_4
    lda #$08
    sta $D020
raster_wait_5:
    lda $D012
    cmp #$5A
    bne raster_wait_5
    lda #$07
    sta $D020
raster_wait_6:
    lda $D012
    cmp #$6E
    bne raster_wait_6
    lda #$05
    sta $D020
raster_wait_7:
    lda $D012
    cmp #$82
    bne raster_wait_7
    lda #$03
    sta $D020
raster_wait_8:
    lda $D012
    cmp #$96
    bne raster_wait_8
    lda #$06
    sta $D020
raster_wait_9:
    lda $D012
    cmp #$AA
    bne raster_wait_9
    lda #$04
    sta $D020
raster_wait_10:
    lda $D012
    cmp #$FA
    bne raster_wait_10
    lda #$00
    sta $D020
    jmp while_start_1
while_exit_2:
    rts                     // Return to BASIC / KERNAL
